# Generated by Django 5.1.6 on 2025-02-18 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=200, null=True, verbose_name='답변')),
                ('answer_count', models.IntegerField(verbose_name='질문순서')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200, null=True, verbose_name='질문')),
                ('answer_type', models.IntegerField(choices=[(0, 'short_subjective'), (1, 'single'), (2, 'multiple')], verbose_name='답변 타입')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('state', models.IntegerField(choices=[(0, 'deleted'), (1, 'in_progress'), (2, 'completed'), (3, 'cancelled')], default=1)),
                ('marketing', models.IntegerField(choices=[(0, 'deleted'), (1, 'in_progress'), (2, 'completed'), (3, 'cancelled')], default=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='work.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='work.question')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, verbose_name='이름')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='연락처')),
                ('prcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='work.process')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='work.question'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.IntegerField(choices=[(0, 'ko'), (1, 'ch')], verbose_name='언어')),
                ('choice', models.CharField(max_length=200, null=True, verbose_name='업무선택')),
                ('work_detail', models.TextField(verbose_name='세부정보')),
                ('detail', models.FileField(blank=True, default='상세화면 이미지', upload_to='detail/%Y/%m/%d/', verbose_name='상세화면 이미지')),
                ('detail_second', models.FileField(blank=True, default='상세화면 이미지', upload_to='detail_second/%Y/%m/%d/', verbose_name='상세화면 이미지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='work.work'),
        ),
        migrations.AddField(
            model_name='process',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='work.work'),
        ),
    ]
