# Generated by Django 5.1.6 on 2025-02-18 07:39

import work.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.IntegerField(default=0, verbose_name='업무순수'),
        ),
        migrations.AlterField(
            model_name='work',
            name='detail',
            field=models.FileField(blank=True, default='상세화면 이미지', upload_to=work.models.at_icon_path, verbose_name='상세화면 이미지'),
        ),
        migrations.AlterField(
            model_name='work',
            name='detail_second',
            field=models.FileField(blank=True, default='상세화면 이미지', upload_to=work.models.at_icon_second, verbose_name='상세화면 이미지'),
        ),
    ]
