# Generated by Django 5.1.6 on 2025-02-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_order_alter_work_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.CharField(max_length=200, null=True, verbose_name='유저'),
        ),
    ]
