# Generated by Django 5.1.6 on 2025-02-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='marketing',
            field=models.CharField(max_length=3, null=True, verbose_name='마케팅 동의여부'),
        ),
        migrations.AlterField(
            model_name='process',
            name='user',
            field=models.CharField(max_length=200, null=True, verbose_name='유저'),
        ),
    ]
