# Generated by Django 5.1.6 on 2025-02-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_process_marketing_alter_process_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='answer',
            field=models.CharField(max_length=200, null=True, verbose_name='답변'),
        ),
        migrations.AlterField(
            model_name='process',
            name='question',
            field=models.CharField(max_length=200, null=True, verbose_name='질문'),
        ),
    ]
