# Generated by Django 5.1.6 on 2025-02-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_process_answer_alter_process_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processuser',
            old_name='prcess',
            new_name='process',
        ),
    ]
