# Generated by Django 5.1.6 on 2025-02-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_prcess_processuser_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='marketing',
        ),
        migrations.RemoveField(
            model_name='process',
            name='state',
        ),
        migrations.AddField(
            model_name='processuser',
            name='marketing',
            field=models.CharField(max_length=3, null=True, verbose_name='마케팅 동의여부'),
        ),
        migrations.AddField(
            model_name='processuser',
            name='state',
            field=models.IntegerField(choices=[(0, 'deleted'), (1, 'in_progress'), (2, 'completed'), (3, 'cancelled')], default=1),
        ),
    ]
