# Generated by Django 5.1.6 on 2025-02-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_processuser_created_at_alter_processuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='processuser',
            name='lang',
            field=models.IntegerField(choices=[(0, '한국어'), (1, '중국어')], default=0),
        ),
        migrations.AlterField(
            model_name='processuser',
            name='state',
            field=models.IntegerField(choices=[(0, '접수완료'), (1, '계약완료'), (2, '서류작성'), (3, '심사진행'), (4, '처리완료'), (5, '상담종료')], default=0),
        ),
    ]
