# Generated by Django 5.1.6 on 2025-03-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_processuser_lang_alter_processuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='match',
            field=models.CharField(max_length=200, null=True, verbose_name='업무진행유저'),
        ),
        migrations.AddField(
            model_name='processuser',
            name='match',
            field=models.CharField(max_length=200, null=True, verbose_name='업무진행유저'),
        ),
    ]
