# Generated by Django 5.1.6 on 2025-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='이메일')),
                ('password', models.CharField(max_length=200, verbose_name='비밀번호')),
                ('sign_in', models.DateTimeField(auto_now_add=True, verbose_name='회원가입')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='로그인')),
                ('bu_name', models.CharField(max_length=50, verbose_name='업체이름')),
                ('bu_post', models.CharField(max_length=50, verbose_name='주소')),
                ('bu_tel_first', models.CharField(max_length=20, verbose_name='1번째 연락처')),
                ('bu_tel_second', models.CharField(max_length=20, verbose_name='2번째 연락처')),
                ('bu_logo', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
