# Generated by Django 5.1.6 on 2025-02-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bu_logo',
            field=models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
