# Generated by Django 5.1.6 on 2025-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bu_post',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bu_tel_second',
        ),
        migrations.AddField(
            model_name='user',
            name='bu_bank_name',
            field=models.CharField(max_length=20, null=True, verbose_name='예금주'),
        ),
        migrations.AddField(
            model_name='user',
            name='bu_bank_number',
            field=models.CharField(max_length=20, null=True, verbose_name='통장 번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='bu_intro',
            field=models.CharField(max_length=50, null=True, verbose_name='업체소개'),
        ),
        migrations.AddField(
            model_name='user',
            name='bu_tel_name',
            field=models.CharField(max_length=20, null=True, verbose_name='담당자 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bu_name',
            field=models.CharField(max_length=50, null=True, verbose_name='업체이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bu_tel_first',
            field=models.CharField(max_length=20, null=True, verbose_name='담당자 연락처'),
        ),
    ]
