# Generated by Django 5.1.6 on 2025-02-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_bu_post_remove_user_bu_tel_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_count',
            field=models.IntegerField(default=0, verbose_name='한국건수'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_count_ch',
            field=models.IntegerField(default=0, verbose_name='중국건수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bu_logo',
            field=models.FileField(blank=True, default='업체로고', upload_to='logo/%Y/%m/%d/'),
        ),
    ]
