# Generated by Django 5.1.6 on 2025-02-18 05:00

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_work_count_user_work_count_ch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bu_logo',
            field=models.FileField(blank=True, default='업체로고', upload_to=user.models.at_icon_path),
        ),
    ]
