# Generated by Django 5.1.6 on 2025-02-18 05:03

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_bu_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bu_logo',
            field=models.FileField(blank=True, null=True, upload_to=user.models.at_icon_path, verbose_name='아이콘 URL'),
        ),
    ]
