# Generated by Django 5.1.6 on 2025-02-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bu_intro_ch',
            field=models.CharField(max_length=50, null=True, verbose_name='업체소개(중국어)'),
        ),
        migrations.AddField(
            model_name='user',
            name='bu_name_ch',
            field=models.CharField(max_length=50, null=True, verbose_name='업체이름(중국어)'),
        ),
    ]
