# Generated by Django 5.1.6 on 2025-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_bu_intro_ch_user_bu_name_ch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_business',
            field=models.IntegerField(default=0, verbose_name='유입되는 회원수'),
        ),
    ]
